/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import com.sun.org.apache.xerces.internal.impl.xpath.regex.Match;
import hotel.db.provider.GuestProvider;
import hotel.entity.Guest;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dedda
 */
public class AddGuestFrame extends javax.swing.JFrame {

    private GuestProvider provider;
    private GuestListFrame guestListFrame;
    
    /**
     * Creates new form AddGuestFrame
     */
    public AddGuestFrame(final GuestListFrame guestListFrame) {
        initComponents();
        setTitle("Neuer Gast");
        provider = new GuestProvider();
        this.guestListFrame = guestListFrame;
        saveBtn.setEnabled(false);
        nameText.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                saveBtn.setEnabled(checkName(nameText.getText()));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                saveBtn.setEnabled(checkName(nameText.getText()));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                saveBtn.setEnabled(checkName(nameText.getText()));
            }
        });
    }

    public boolean checkName(final String name) {
        final String expression = "[A-Z][a-z]+\\s[A-Z][a-z]+";
        if (!name.matches(expression)) {
            return false;
        }
        if (name.split(" ")[0].length() > 30) {
            return false;
        }
        if (name.split(" ")[1].length() > 30) {
            return false;
        }
        if (provider.getForName(name) == null) {
            return true;
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JTextField();
        haederLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        haederLbl.setText("Neuer Gast");

        saveBtn.setText("speichern");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(haederLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(haederLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Guest guest = new Guest();
        guest.setName(nameText.getText().split(" ")[0]);
        guest.setSurname(nameText.getText().split(" ")[1]);
        provider.saveNew(guest);
        setVisible(true);
        guestListFrame.loadGuests();
        dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel haederLbl;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
