/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.db.provider.RoomProvider;
import hotel.db.provider.ServiceProvider;
import hotel.entity.Guest;
import hotel.entity.Reservation;
import hotel.entity.Room;
import hotel.gui.model.RoomComboBoxModel;
import java.util.Date;
import java.util.List;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author schaefal, dedda
 */
public class AddReservationFrame extends javax.swing.JFrame {

    private RoomProvider roomProvider;
    private ServiceProvider serviceProvider;
    private Guest guest;
    
    /**
     * Creates new form HotelOberfläche
     */
    public AddReservationFrame(final Guest guest) {
        this.guest = guest;
        roomProvider = new RoomProvider();
        serviceProvider = new ServiceProvider();
        initComponents();
        setTitle("Reservierungen");
        setLocationRelativeTo(null);
        nameTextLbl.setText(guest.getName() + " " + guest.getSurname());
        
    }
    
    private Date getStartDate() {
        SpinnerDateModel model = (SpinnerDateModel) arrivalSpinner.getModel();
        return model.getDate();
    }
    
    private Date getEndDate() {
        SpinnerDateModel model = (SpinnerDateModel) departureSpinner.getModel();
        return model.getDate();
    }
    
    private void loadRooms() {
        Date arrival = getStartDate();
        Date departure = getEndDate();
        List<Room> freeRooms = roomProvider.getFree(arrival, departure);
        RoomComboBoxModel comboBoxModel = new RoomComboBoxModel();
        comboBoxModel.setRooms(freeRooms);
        roomBox.setModel(comboBoxModel);
        roomBox.setSelectedIndex(0);
    }
    
    private void inputUpdated() {
        boolean validInput = true;
        Date arrival = getStartDate();
        Date departure = getEndDate();
        if (arrival.before(new Date())) {
            validInput = false;
        }
        if (departure.before(arrival)
                || departure.before(new Date())) {
            validInput = false;
        }
        SpinnerNumberModel peopleSpinnerModel = (SpinnerNumberModel) peopleSpinner.getModel();
        if (selectedRoomList.getModel().getSize() > (int) peopleSpinnerModel.getNumber()) {
            validInput = false;
        }
        
        saveBtn.setEnabled(validInput);
        
    }
    
    private Reservation buildReservation() {
        Reservation reservation = new Reservation();
        reservation.setAdditionalInfo(infoArea.getText());
        reservation.setCanceled(null);
        reservation.setGuest(guest);
        reservation.setStart(getStartDate());
        reservation.setEnd(getEndDate());
        reservation.setPayed(payedBox.isSelected() ? new Date() : null);
        return reservation;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        arrivalLbl = new javax.swing.JLabel();
        departureLbl = new javax.swing.JLabel();
        peopleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableServicesList = new javax.swing.JList();
        addServiceBtn = new javax.swing.JButton();
        removeServiceBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedServicesList = new javax.swing.JList();
        arrivalSpinner = new javax.swing.JSpinner();
        departureSpinner = new javax.swing.JSpinner();
        peopleSpinner = new javax.swing.JSpinner();
        nameLbl = new javax.swing.JLabel();
        nameTextLbl = new javax.swing.JLabel();
        roomsLbl = new javax.swing.JLabel();
        roomBox = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedRoomList = new javax.swing.JList();
        addRoom = new javax.swing.JButton();
        removeRoom = new javax.swing.JButton();
        roomInfoBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        additionalInfoLbl = new javax.swing.JLabel();
        payedBox = new javax.swing.JCheckBox();

        saveBtn.setText("Speichern");
        saveBtn.setEnabled(false);

        cancelBtn.setText("Cancel");

        arrivalLbl.setText("Ankunft");

        departureLbl.setText("Abreise");

        peopleLbl.setText("Anzahl Personen");

        jScrollPane1.setViewportView(availableServicesList);

        addServiceBtn.setText(">>");

        removeServiceBtn.setText("<<");

        jScrollPane2.setViewportView(selectedServicesList);

        arrivalSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.MONTH));

        departureSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.MONTH));

        peopleSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        nameLbl.setText("Gast:");

        roomsLbl.setText("Räume:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(arrivalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(departureSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(peopleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrivalLbl)
                            .addComponent(peopleLbl)
                            .addComponent(departureLbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(roomsLbl)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addServiceBtn)
                    .addComponent(removeServiceBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(addServiceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeServiceBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLbl)
                        .addComponent(nameTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(arrivalLbl)
                        .addComponent(arrivalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departureSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(departureLbl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(peopleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(peopleLbl))
                    .addGap(54, 54, 54)
                    .addComponent(roomsLbl))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        jScrollPane3.setViewportView(selectedRoomList);

        addRoom.setText(">>");

        removeRoom.setText("<<");

        roomInfoBtn.setText("Info");

        infoArea.setColumns(20);
        infoArea.setRows(5);
        jScrollPane4.setViewportView(infoArea);

        additionalInfoLbl.setText("Anmerkungen:");

        payedBox.setText("schon bezahlt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roomInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeRoom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addRoom))
                                    .addComponent(additionalInfoLbl, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn))
                            .addComponent(payedBox))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRoom)
                            .addComponent(removeRoom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomInfoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(additionalInfoLbl))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(payedBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(cancelBtn)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoom;
    private javax.swing.JButton addServiceBtn;
    private javax.swing.JLabel additionalInfoLbl;
    private javax.swing.JLabel arrivalLbl;
    private javax.swing.JSpinner arrivalSpinner;
    private javax.swing.JList availableServicesList;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel departureLbl;
    private javax.swing.JSpinner departureSpinner;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameTextLbl;
    private javax.swing.JCheckBox payedBox;
    private javax.swing.JLabel peopleLbl;
    private javax.swing.JSpinner peopleSpinner;
    private javax.swing.JButton removeRoom;
    private javax.swing.JButton removeServiceBtn;
    private javax.swing.JComboBox roomBox;
    private javax.swing.JButton roomInfoBtn;
    private javax.swing.JLabel roomsLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JList selectedRoomList;
    private javax.swing.JList selectedServicesList;
    // End of variables declaration//GEN-END:variables
}
